Sponsorship
ppijerman/iconic-24 pull request #31
Opened 2024-07-20 16:37 UTC by imeldaputr

2024-07-20 19:19 UTC, kunkoala requested changes
Thank you mell!! Udah bagus bangeeet dan sesuai sama kebutuhann menurut gua, mungkin nanti masalah rebase2 apa gak usah dulu deh, langsung gua merge pull ajaa hehe. THank you yakkk!

2024-07-20 19:19 UTC, kunkoala commented on app/partnership/page.tsx
> +          <div className="sm:w-fit flex p-5 pe-0.5 justify-between sm:justify-center bg-[#66d998] rounded shadow-lg">
mel, ini lebih enak jadi bg-gray-100 atau bg-gray-200

```suggestion
          <div className="sm:w-fit flex p-5 pe-0.5 justify-between sm:justify-center bg-gray-100 rounded shadow-lg">
```

atau 

```suggestion
          <div className="sm:w-fit flex p-5 pe-0.5 justify-between sm:justify-center bg-gray-200 rounded shadow-lg">
```

2024-07-20 19:19 UTC, kunkoala commented on app/partnership/page.tsx
> +          <div className="sm:w-fit flex p-5 pe-0.5 justify-between sm:justify-center bg-[#66d998] rounded shadow-lg">
btw kalo warna teks nya jadi gak keliatan mungkin bisa agak gelapan, make sure keliatan ajaa sii.

Ato preferably pake accent2 atau secondary

2024-07-20 19:19 UTC, kunkoala commented on app/partnership/page.tsx
> +            <Image src={logoEcadin} alt="Logo Ecadin" width="150" height="150" className=""/>
ini logo ecadin nya di gua agak gak bagus resolusi nyaa, mungkin bisa di bagusin lagii 

![image](https://github.com/user-attachments/assets/faa3b2f8-00af-4a8d-ae6d-1bd03445f5b1)


mungkin bisa di setting heightnya aja biar menyesuaikan dia widthnya, atau sebaliknya...

2024-07-26 18:17 UTC, imeldaputr commented on app/partnership/page.tsx
> +          <div className="sm:w-fit flex p-5 pe-0.5 justify-between sm:justify-center bg-[#66d998] rounded shadow-lg">
soalnya logo ecadinnya warna putih ca

2024-07-26 18:48 UTC, kunkoala approved these changes

2024-07-26 18:48 UTC, merged